version: '3'

services:
  app:
    build: .
    image: api
    container_name: api
    working_dir: /var/www
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
      - ./setup/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  webserver:
    image: nginx:alpine
    container_name: nginxapi
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
      - ./setup/:/etc/nginx/conf.d/
    ports:
      - "1990:80"
    networks:
      - laravel

  # # WITH MYSQL
  # db:
  #   image: mysql:5.7.39
  #   container_name: dbapi
  #   restart: always
  #   tty: true
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #     - ./setup/my.cnf:/etc/my.cnf
  #   ports:
  #     - "33066:3306"
  #   environment:
  #     MYSQL_DATABASE: api
  #     MYSQL_USER: apiuser
  #     MYSQL_PASSWORD: apipassword
  #     MYSQL_ROOT_PASSWORD: apipassword
  #   networks:
  #     - laravel

  #WITH POSTGRES
  db:
    image: postgres
    container_name: dbapi
    restart: always
    tty: true
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: apipassword
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

# JIKA MENGGUNAKAN MYSQL AKTIFKAN INI
# volumes:
#   dbdata:
#     driver: local

# JIKA MENGGUNAKAN POSTGRES AKTIFKAN INI
volumes:
  pgdata:
    driver: local
